[package]
name = "std_specs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"prusti-contracts" = { git = "https://github.com/viperproject/prusti-dev" }
